"""L-Bracket with Gussets â€” Generated by Claude CLI
L-bracket with triangular reinforcement ribs and mounting holes.
Export: bracket in STEP and STL.
"""
import cadquery as cq
import os

# === MAIN PARAMETERS ===
arm_h      = 50.0    # [mm] vertical arm height
arm_w      = 40.0    # [mm] horizontal arm width
thickness  = 4.0     # [mm] bracket thickness
depth      = 30.0    # [mm] depth (Y axis)

# === HOLE PARAMETERS ===
n_holes_v  = 2       # number of holes on vertical arm
n_holes_h  = 2       # number of holes on horizontal arm
hole_d     = 3.4     # [mm] through-hole diameter (M3 clearance)
hole_margin = 10.0   # [mm] first hole distance from edge

# === PRINT PARAMETERS ===
fillet_r   = 2.0     # [mm] outer corner fillet radius
inner_r    = 3.0     # [mm] inner L-corner fillet radius

# === RIB PARAMETERS ===
n_gussets    = 2       # number of triangular ribs
gusset_h     = 15.0    # [mm] rib height on vertical arm
gusset_w     = 15.0    # [mm] rib extension on horizontal arm
gusset_thick = 3.0     # [mm] rib thickness

# === OUTPUT ===
out_dir = os.path.dirname(os.path.abspath(__file__))


def make_l_profile():
    """Creates the L-profile as a 2D extrusion."""
    # L-profile in XZ plane
    profile = (
        cq.Workplane("XZ")
        .moveTo(0, 0)
        .lineTo(arm_w, 0)
        .lineTo(arm_w, thickness)
        .lineTo(thickness, thickness)
        .lineTo(thickness, arm_h)
        .lineTo(0, arm_h)
        .close()
        .extrude(depth)
    )
    return profile


def make_inner_fillet(body):
    """Applies fillet to the inner L-corner (before gussets)."""
    # Select only the inner corner edge (x=thickness, z=thickness)
    inner_edge_pt = (thickness, depth / 2, thickness)
    body = (
        body
        .edges(cq.selectors.NearestToPointSelector(inner_edge_pt))
        .fillet(inner_r)
    )
    return body


def add_holes_vertical(body):
    """Holes on the vertical arm (face toward the wall)."""
    if n_holes_v == 0:
        return body
    spacing = (arm_h - 2 * hole_margin) / max(n_holes_v - 1, 1)
    pts = [(0, hole_margin + i * spacing) for i in range(n_holes_v)]
    body = (
        body
        .faces("<X")
        .workplane()
        .center(depth / 2, 0)
        .pushPoints(pts)
        .hole(hole_d)
    )
    return body


def add_holes_horizontal(body):
    """Holes on the horizontal arm (bottom face)."""
    if n_holes_h == 0:
        return body
    spacing = (arm_w - 2 * hole_margin) / max(n_holes_h - 1, 1)
    pts = [(hole_margin + i * spacing, 0) for i in range(n_holes_h)]
    body = (
        body
        .faces("<Z")
        .workplane()
        .center(-arm_w / 2, depth / 2)
        .pushPoints(pts)
        .hole(hole_d)
    )
    return body


def add_gussets(body):
    """Adds triangular reinforcement ribs in the corner."""
    if n_gussets == 0:
        return body
    gusset_spacing = depth / (n_gussets + 1)
    for i in range(n_gussets):
        y_pos = gusset_spacing * (i + 1)
        gusset = (
            cq.Workplane("XZ")
            .moveTo(thickness, thickness)
            .lineTo(thickness + gusset_w, thickness)
            .lineTo(thickness, thickness + gusset_h)
            .close()
            .extrude(gusset_thick)
            .translate((0, y_pos - gusset_thick / 2, 0))
        )
        body = body.union(gusset)
    return body


def make_assembly():
    """Assembles the complete bracket."""
    body = make_l_profile()
    body = make_inner_fillet(body)   # fillet BEFORE gussets
    body = add_gussets(body)
    body = add_holes_vertical(body)
    body = add_holes_horizontal(body)
    return body


# === EXPORT ===
result = make_assembly()

step_path = os.path.join(out_dir, "bracket.step")
stl_path  = os.path.join(out_dir, "bracket.stl")
cq.exporters.export(result, step_path)
cq.exporters.export(result, stl_path)

bb = result.val().BoundingBox()
vol = result.val().Volume()
print(f"BRACKET: {bb.xlen:.2f} x {bb.ylen:.2f} x {bb.zlen:.2f} mm, vol={vol:.0f} mm3")
print(f"Files: {step_path}, {stl_path}")
