"""Parametric Box with Lid â€” Generated by Claude CLI
Parametric box with interlocking lid and optional snap-fit.
Export: body + lid in STEP and STL.
"""
import cadquery as cq
import os

# === MAIN PARAMETERS ===
inner_w  = 60.0    # [mm] internal width
inner_d  = 40.0    # [mm] internal depth
inner_h  = 25.0    # [mm] internal height

# === PRINT PARAMETERS ===
wall     = 2.0     # [mm] wall thickness
floor_t  = 1.6     # [mm] floor thickness
lid_t    = 1.6     # [mm] lid thickness
fillet_r = 2.0     # [mm] vertical corner fillet radius
lip_h    = 3.0     # [mm] lid interlocking lip height
lip_gap  = 0.3     # [mm] lip clearance

# === SNAP-FIT PARAMETERS ===
snap_fit     = True    # enable/disable snap-fit
snap_w       = 4.0     # [mm] snap-fit tab width
snap_h       = 2.0     # [mm] snap-fit tab height
snap_lip     = 0.8     # [mm] snap lip overhang
snap_thick   = 1.2     # [mm] tab thickness

# === DERIVED PARAMETERS ===
outer_w  = inner_w + 2 * wall              # [mm]
outer_d  = inner_d + 2 * wall              # [mm]
outer_h  = inner_h + floor_t               # [mm] external body height
lid_outer_h = lid_t + lip_h                # [mm] total lid height

# === OUTPUT ===
out_dir = os.path.dirname(os.path.abspath(__file__))


def make_body():
    """Box body: outer shell - internal cavity + fillet."""
    outer = (
        cq.Workplane("XY")
        .box(outer_w, outer_d, outer_h)
        .translate((0, 0, outer_h / 2))
    )
    cavity = (
        cq.Workplane("XY")
        .box(inner_w, inner_d, inner_h)
        .translate((0, 0, floor_t + inner_h / 2))
    )
    body = outer.cut(cavity)
    body = body.edges("|Z").fillet(fillet_r)
    return body


def make_body_snap(body):
    """Adds snap-fit slots on the long walls of the body."""
    if not snap_fit:
        return body
    # Rectangular slots in Y walls (long sides)
    for y_sign in [1, -1]:
        y_pos = y_sign * (outer_d / 2)
        slot = (
            cq.Workplane("XZ")
            .center(0, floor_t + inner_h - snap_h / 2)
            .rect(snap_w + 0.4, snap_h + 0.4)
            .extrude(wall + 1)
            .translate((0, y_pos - y_sign * (wall / 2 + 0.5), 0))
        )
        body = body.cut(slot)
    return body


def make_lid():
    """Lid with interlocking lip."""
    # Flat top plate
    top = (
        cq.Workplane("XY")
        .box(outer_w, outer_d, lid_t)
        .translate((0, 0, lid_t / 2))
    )
    # Lip that fits inside the box
    lip_w = inner_w - 2 * lip_gap   # [mm]
    lip_d = inner_d - 2 * lip_gap   # [mm]
    lip = (
        cq.Workplane("XY")
        .box(lip_w, lip_d, lip_h)
        .translate((0, 0, -lip_h / 2))
    )
    # Hollow out the lip to save material
    lip_cavity = (
        cq.Workplane("XY")
        .box(lip_w - 2 * wall, lip_d - 2 * wall, lip_h + 1)
        .translate((0, 0, -lip_h / 2))
    )
    lid = top.union(lip).cut(lip_cavity)
    lid = lid.edges("|Z").fillet(fillet_r)
    return lid


def make_lid_snap(lid):
    """Adds snap-fit tabs to the lid."""
    if not snap_fit:
        return lid
    lip_d_actual = inner_d - 2 * lip_gap  # [mm]
    for y_sign in [1, -1]:
        y_base = y_sign * (lip_d_actual / 2 - wall)
        # Tab: small protrusion on the lip
        tab = (
            cq.Workplane("XZ")
            .center(0, -lip_h + snap_h / 2)
            .rect(snap_w, snap_h)
            .extrude(snap_lip)
            .translate((0, y_base + y_sign * snap_lip / 2, 0))
        )
        lid = lid.union(tab)
    return lid


def make_assembly():
    """Assembles body and lid."""
    body = make_body()
    body = make_body_snap(body)
    lid = make_lid()
    lid = make_lid_snap(lid)
    return body, lid


# === EXPORT ===
body, lid = make_assembly()

# Body
body_step = os.path.join(out_dir, "body.step")
body_stl  = os.path.join(out_dir, "body.stl")
cq.exporters.export(body, body_step)
cq.exporters.export(body, body_stl)

# Lid
lid_step = os.path.join(out_dir, "lid.step")
lid_stl  = os.path.join(out_dir, "lid.stl")
cq.exporters.export(lid, lid_step)
cq.exporters.export(lid, lid_stl)

# Info
for name, part in [("BODY", body), ("LID", lid)]:
    bb = part.val().BoundingBox()
    vol = part.val().Volume()
    print(f"{name}: {bb.xlen:.2f} x {bb.ylen:.2f} x {bb.zlen:.2f} mm, vol={vol:.0f} mm3")

print(f"Files: {body_step}, {body_stl}, {lid_step}, {lid_stl}")
