"""Snap-Fit Cantilever â€” Generated by Claude CLI
Parametric cantilever snap-fit module for snap-together joints.
Exportable as a single part to join with other bodies.
Export: snap_fit in STEP and STL.
"""
import cadquery as cq
import math
import os

# === MAIN PARAMETERS ===
beam_length  = 12.0    # [mm] cantilever beam length
beam_width   = 5.0     # [mm] beam width
beam_thick   = 1.2     # [mm] beam thickness
lip_height   = 1.0     # [mm] lip height (catch overhang)
lip_angle    = 30.0    # [deg] insertion ramp angle

# === PRINT PARAMETERS ===
base_width   = 8.0     # [mm] attachment base width
base_height  = 4.0     # [mm] attachment base height
base_depth   = 3.0     # [mm] base depth (host wall thickness)
fillet_r     = 0.5     # [mm] fillet at cantilever root

# === DERIVED PARAMETERS ===
lip_ramp = lip_height / math.tan(math.radians(lip_angle))  # [mm] ramp length

# === OUTPUT ===
out_dir = os.path.dirname(os.path.abspath(__file__))


def make_base():
    """Attachment base block for the wall."""
    base = (
        cq.Workplane("XY")
        .box(base_depth, base_width, base_height)
        .translate((base_depth / 2, 0, base_height / 2))
    )
    return base


def make_cantilever():
    """Cantilever beam extending from the base."""
    cantilever = (
        cq.Workplane("XY")
        .box(beam_length, beam_width, beam_thick)
        .translate((
            base_depth + beam_length / 2,
            0,
            base_height - beam_thick / 2,
        ))
    )
    return cantilever


def make_lip():
    """Catch lip with insertion ramp at the cantilever tip."""
    lip_x = base_depth + beam_length  # [mm] X position of cantilever tip

    # Lip profile in XZ plane: rectangle + triangular ramp
    lip_profile = (
        cq.Workplane("XZ")
        .moveTo(lip_x, base_height - beam_thick)
        .lineTo(lip_x, base_height - beam_thick + lip_height)
        .lineTo(lip_x + lip_ramp, base_height - beam_thick)
        .close()
        .extrude(beam_width / 2, both=True)
    )

    # Vertical part of the lip
    lip_block = (
        cq.Workplane("XY")
        .box(beam_thick, beam_width, lip_height)
        .translate((
            lip_x - beam_thick / 2,
            0,
            base_height - beam_thick + lip_height / 2,
        ))
    )

    return lip_block.union(lip_profile)


def make_assembly():
    """Assembles the complete snap-fit module."""
    base = make_base()
    cantilever = make_cantilever()
    lip = make_lip()

    # Union of all parts
    snap = base.union(cantilever).union(lip)

    # Fillet at cantilever root
    # Applied on edges at the base-cantilever junction
    try:
        snap = snap.edges("|Y").fillet(fillet_r)
    except Exception:
        pass  # fillet may fail on complex geometries

    return snap


# === EXPORT ===
result = make_assembly()

step_path = os.path.join(out_dir, "snap_fit.step")
stl_path  = os.path.join(out_dir, "snap_fit.stl")
cq.exporters.export(result, step_path)
cq.exporters.export(result, stl_path)

bb = result.val().BoundingBox()
vol = result.val().Volume()
print(f"SNAP_FIT: {bb.xlen:.2f} x {bb.ylen:.2f} x {bb.zlen:.2f} mm, vol={vol:.0f} mm3")
print(f"Files: {step_path}, {stl_path}")
