"""Threaded Insert Bosses â€” Generated by Claude CLI
Heat insert holes for M2/M3/M4/M5 with cylindrical reinforcement bosses.
Generates a demo plate with all 4 sizes.
Export: insert_boss in STEP and STL.
"""
import cadquery as cq
import os

# === HEAT INSERT TABLE ===
# (name, hole_diameter [mm], hole_depth [mm], boss_diameter [mm])
INSERT_TABLE = {
    "M2":  (3.2,  5.0,  6.0),
    "M3":  (4.2,  6.0,  8.0),
    "M4":  (5.6,  8.0, 10.0),
    "M5":  (6.4, 10.0, 12.0),
}

# === MAIN PARAMETERS ===
inserts_to_build = ["M2", "M3", "M4", "M5"]   # sizes to generate
spacing          = 20.0                         # [mm] center-to-center distance

# === PRINT PARAMETERS ===
plate_thick  = 3.0     # [mm] base plate thickness
plate_margin = 10.0    # [mm] margin around bosses
fillet_r     = 1.0     # [mm] fillet at boss base
chamfer_top  = 0.5     # [mm] chamfer on boss top

# === DERIVED PARAMETERS ===
n_inserts = len(inserts_to_build)
plate_w   = (n_inserts - 1) * spacing + 2 * plate_margin  # [mm]
plate_d   = 2 * plate_margin                               # [mm]

# === OUTPUT ===
out_dir = os.path.dirname(os.path.abspath(__file__))


def make_plate():
    """Rectangular base plate."""
    plate = (
        cq.Workplane("XY")
        .box(plate_w, plate_d, plate_thick)
        .translate((0, 0, plate_thick / 2))
    )
    return plate


def add_bosses(plate):
    """Adds cylindrical bosses with heat insert holes."""
    start_x = -(n_inserts - 1) * spacing / 2

    for i, name in enumerate(inserts_to_build):
        hole_d, hole_depth, boss_d = INSERT_TABLE[name]
        cx = start_x + i * spacing

        boss_h = hole_depth + 1.0  # [mm] boss slightly taller than hole

        # Cylindrical boss
        boss = (
            cq.Workplane("XY")
            .circle(boss_d / 2)
            .extrude(boss_h)
            .translate((cx, 0, plate_thick))
        )
        plate = plate.union(boss)

        # Heat insert hole
        hole = (
            cq.Workplane("XY")
            .circle(hole_d / 2)
            .extrude(hole_depth)
            .translate((cx, 0, plate_thick + boss_h - hole_depth))
        )
        plate = plate.cut(hole)

    return plate


def add_fillets_and_chamfers(body):
    """Fillets at boss base and chamfer on top."""
    try:
        body = body.edges("|Z").fillet(fillet_r)
    except Exception:
        pass  # fillet on complex geometries may partially fail
    return body


def make_assembly():
    """Assembles plate with bosses."""
    plate = make_plate()
    plate = add_bosses(plate)
    plate = add_fillets_and_chamfers(plate)
    return plate


# === EXPORT ===
result = make_assembly()

step_path = os.path.join(out_dir, "insert_boss.step")
stl_path  = os.path.join(out_dir, "insert_boss.stl")
cq.exporters.export(result, step_path)
cq.exporters.export(result, stl_path)

bb = result.val().BoundingBox()
vol = result.val().Volume()
print(f"INSERT_BOSS: {bb.xlen:.2f} x {bb.ylen:.2f} x {bb.zlen:.2f} mm, vol={vol:.0f} mm3")

# Print details for each insert
for name in inserts_to_build:
    hole_d, hole_depth, boss_d = INSERT_TABLE[name]
    print(f"  {name}: hole dia {hole_d:.1f} x {hole_depth:.1f}mm, boss dia {boss_d:.1f}mm")

print(f"Files: {step_path}, {stl_path}")
