"""Credit Card Holder — Snap-Fit Lid
Generated by Claude CLI — 2026-02-13
Credit card holder with snap-fit closure.
Card dimensions: ISO 7810 ID-1 (85.6 x 53.98 mm)
Material: PLA (wall_min=1.0mm, density=1.24 g/cm3)
"""
import cadquery as cq
import os

# === CREDIT CARD PARAMETERS (ISO 7810) ===
card_w       = 85.6     # [mm] card width
card_d       = 53.98    # [mm] card depth
clearance    = 1.0      # [mm] clearance around cards

# === BOX PARAMETERS ===
wall         = 2.0      # [mm] wall thickness (> PLA wall_min 1.0mm)
floor_t      = 1.6      # [mm] floor thickness
outer_h      = 40.0     # [mm] external body height
fillet_r     = 1.0      # [mm] vertical corner fillet radius

# === DERIVED PARAMETERS ===
inner_w      = card_w + 2 * clearance    # [mm] 87.6
inner_d      = card_d + 2 * clearance    # [mm] 55.98
inner_h      = outer_h - floor_t         # [mm] 38.4
outer_w      = inner_w + 2 * wall        # [mm] 91.6
outer_d      = inner_d + 2 * wall        # [mm] 59.98

# === THUMB NOTCH PARAMETERS ===
notch_w      = 25.0     # [mm] thumb notch width
notch_h      = 12.0     # [mm] notch depth from top

# === LID + SNAP-FIT PARAMETERS ===
lid_t        = 1.6      # [mm] lid thickness
lip_h        = 3.0      # [mm] interlocking lip height
lip_gap      = 0.3      # [mm] lip clearance
snap_w       = 10.0     # [mm] snap-fit hook width
snap_h       = 2.0      # [mm] hook height
snap_overhang = 0.8     # [mm] hook overhang

# === OUTPUT ===
out_dir = os.path.dirname(os.path.abspath(__file__))


def make_outer_shell():
    """Outer box with fillet on vertical edges — BEFORE booleans."""
    outer = (
        cq.Workplane("XY")
        .box(outer_w, outer_d, outer_h)
        .translate((0, 0, outer_h / 2))
        .edges("|Z")
        .fillet(fillet_r)
    )
    return outer


def make_cavity(outer):
    """Hollows out the internal cavity."""
    cavity = (
        cq.Workplane("XY")
        .box(inner_w, inner_d, inner_h)
        .translate((0, 0, floor_t + inner_h / 2))
    )
    return outer.cut(cavity)


def add_thumb_notch(body):
    """Rectangular notch on front side for card extraction."""
    notch = (
        cq.Workplane("XY")
        .box(notch_w, wall + 2, notch_h)
        .translate((0, outer_d / 2, outer_h - notch_h / 2))
    )
    return body.cut(notch)


def add_snap_recesses(body):
    """Snap-fit recesses on internal walls (long Y sides)."""
    for y_sign in [1, -1]:
        y_pos = y_sign * (outer_d / 2 - wall / 2)   # [mm] wall center
        recess = (
            cq.Workplane("XY")
            .box(snap_w, wall + 1, snap_h)
            .translate((0, y_pos, outer_h - snap_h / 2))
        )
        body = body.cut(recess)
    return body


def make_body():
    """Assembles the box body."""
    body = make_outer_shell()
    body = make_cavity(body)
    body = add_thumb_notch(body)
    body = add_snap_recesses(body)
    return body


def make_lid():
    """Lid with interlocking lip and snap-fit hooks."""
    # Flat top plate
    top = (
        cq.Workplane("XY")
        .box(outer_w, outer_d, lid_t)
        .translate((0, 0, lid_t / 2))
        .edges("|Z")
        .fillet(fillet_r)
    )

    # Interlocking lip (frame that fits inside the cavity)
    lip_w = inner_w - 2 * lip_gap    # [mm]
    lip_d = inner_d - 2 * lip_gap    # [mm]
    lip_outer = (
        cq.Workplane("XY")
        .box(lip_w, lip_d, lip_h)
        .translate((0, 0, -lip_h / 2))
    )
    lip_inner = (
        cq.Workplane("XY")
        .box(lip_w - 2 * wall, lip_d - 2 * wall, lip_h + 1)
        .translate((0, 0, -lip_h / 2))
    )
    lid = top.union(lip_outer).cut(lip_inner)

    # Snap-fit hooks (2 hooks on long Y sides, centered)
    for y_sign in [1, -1]:
        y_base = y_sign * (lip_d / 2 - wall / 2)   # [mm]
        hook = (
            cq.Workplane("XY")
            .box(snap_w, snap_overhang, snap_h)
            .translate((
                0,
                y_base + y_sign * snap_overhang / 2,
                -lip_h + snap_h / 2
            ))
        )
        lid = lid.union(hook)

    return lid


# === EXPORT ===
body = make_body()
lid = make_lid()

# Body
body_step = os.path.join(out_dir, "credit_card_holder.step")
body_stl  = os.path.join(out_dir, "credit_card_holder.stl")
cq.exporters.export(body, body_step)
cq.exporters.export(body, body_stl)

# Lid
lid_step = os.path.join(out_dir, "credit_card_holder_lid.step")
lid_stl  = os.path.join(out_dir, "credit_card_holder_lid.stl")
cq.exporters.export(lid, lid_step)
cq.exporters.export(lid, lid_stl)

# Assembly
assy = cq.Assembly()
assy.add(body, name="body", color=cq.Color(0.27, 0.51, 0.71))
assy.add(
    lid, name="lid",
    loc=cq.Location((0, 0, outer_h + 2)),
    color=cq.Color(0.9, 0.9, 0.9)
)
assy_step = os.path.join(out_dir, "credit_card_holder_assembly.step")
assy.save(assy_step)

# === REPORT ===
print("=" * 55)
print("  REPORT — Credit Card Holder (PLA)")
print("=" * 55)

for name, part in [("BODY", body), ("LID", lid)]:
    bb = part.val().BoundingBox()
    vol = part.val().Volume()
    vol_cm3 = vol / 1000
    weight_g = vol_cm3 * 1.24 * (0.3 + 0.7 * 0.20)
    time_h = (vol_cm3 / 20) * 1.3
    hours = int(time_h)
    minutes = int((time_h - hours) * 60)

    print(f"\n{name}:")
    print(f"  BB: {bb.xlen:.1f} x {bb.ylen:.1f} x {bb.zlen:.1f} mm")
    print(f"  Volume: {vol:,.0f} mm3 ({vol_cm3:.1f} cm3)")
    print(f"  Estimated weight: {weight_g:.1f}g (PLA, 20% infill)")
    print(f"  Estimated time: ~{hours}h {minutes}min")

print(f"\nMaterial: PLA")
print(f"  wall_min: 1.0mm (used: {wall}mm) OK")
print(f"  Fillet: {fillet_r}mm on vertical edges")
print(f"  Enclosed chamber: not required")

print(f"\nInternal dimensions:")
print(f"  Width: {inner_w:.1f}mm (card {card_w}+clearance)")
print(f"  Depth: {inner_d:.1f}mm (card {card_d}+clearance)")
print(f"  Internal height: {inner_h:.1f}mm (~{int(inner_h / 0.76)} cards)")

print(f"\nSnap-fit: 2 hooks ({snap_w}x{snap_h}mm)")
print(f"Thumb notch: {notch_w}x{notch_h}mm (front side)")

print(f"\nPrint orientation: Z-up (base down)")
print(f"Supports: not needed")

print(f"\nExported files:")
print(f"  {body_step}")
print(f"  {body_stl}")
print(f"  {lid_step}")
print(f"  {lid_stl}")
print(f"  {assy_step}")
print("=" * 55)
