"""Arduino Uno Rev3 Enclosure — End-to-End 3D Print Pipeline Test
Generated by Claude CLI — 2026-02-13
Enclosure for Arduino Uno Rev3 + mini breadboard 47x35mm.
Snap-fit closure, ventilation grid, USB-B and DC jack openings.
Material: PETG (wall_min=1.2mm, density=1.27 g/cm3)
"""
import cadquery as cq
import os

# === ARDUINO UNO REV3 PCB PARAMETERS ===
pcb_w       = 68.6     # [mm] Arduino PCB width
pcb_d       = 53.4     # [mm] Arduino PCB depth
pcb_thick   = 1.6      # [mm] PCB thickness
comp_h      = 15.0     # [mm] max component height above PCB
pcb_clearance = 1.0    # [mm] clearance around PCB

# === MINI BREADBOARD PARAMETERS ===
bb_w        = 47.0     # [mm] mini breadboard width
bb_d        = 35.0     # [mm] mini breadboard depth
bb_gap      = 3.0      # [mm] gap between Arduino and breadboard

# === ARDUINO MOUNTING HOLE PARAMETERS ===
# Positions relative to the bottom-left corner of the PCB
arduino_holes = [
    (13.97,  2.54),     # [mm] hole 1
    (66.04,  7.62),     # [mm] hole 2
    (66.04, 35.56),     # [mm] hole 3
    (15.24, 50.80),     # [mm] hole 4
]
mount_hole_d   = 3.2    # [mm] M3 through-hole diameter
standoff_od    = 6.0    # [mm] standoff outer diameter
standoff_h     = 5.0    # [mm] standoff height

# === PRINT PARAMETERS (PETG) ===
wall         = 2.0      # [mm] wall thickness (> PETG wall_min 1.2mm)
floor_t      = 1.6      # [mm] floor thickness
fillet_r     = 1.5      # [mm] outer vertical corner fillet radius
clearance    = 0.3      # [mm] general clearance

# === APERTURE PARAMETERS ===
# USB-B: on the short side where X = pcb_w (right side of Arduino)
usb_w        = 12.0     # [mm] USB-B opening width
usb_h        = 10.9     # [mm] USB-B opening height
usb_y_center = 31.5     # [mm] USB-B center from bottom edge of PCB

# DC jack: same side as USB-B
dc_w         = 9.0      # [mm] DC jack opening width
dc_h         = 11.0     # [mm] DC jack opening height
dc_y_center  = 7.0      # [mm] DC jack center from bottom edge of PCB

# === LID + SNAP-FIT PARAMETERS ===
lid_t        = 1.6      # [mm] lid thickness
lip_h        = 3.0      # [mm] interlocking lip height
lip_gap      = 0.3      # [mm] lip clearance
snap_w       = 8.0      # [mm] snap-fit hook width
snap_h       = 2.0      # [mm] hook height
snap_depth   = 1.0      # [mm] snap undercut depth
snap_overhang = 0.8     # [mm] hook overhang

# === VENTILATION PARAMETERS ===
vent_slot_w  = 2.0      # [mm] single vent slot width
vent_slot_l  = 30.0     # [mm] vent slot length
vent_gap     = 3.0      # [mm] vent slot pitch (center-to-center)
vent_n       = 8        # number of vent slots

# === DERIVED PARAMETERS ===
# Internal layout: [Arduino] [gap] [breadboard]
inner_w = pcb_w + bb_gap + bb_w + 2 * pcb_clearance          # [mm]
inner_d = max(pcb_d, bb_d) + 2 * pcb_clearance               # [mm]
inner_h = standoff_h + pcb_thick + comp_h                      # [mm]
outer_w = inner_w + 2 * wall                                   # [mm]
outer_d = inner_d + 2 * wall                                   # [mm]
outer_h = inner_h + floor_t                                    # [mm]

# Arduino PCB offset: centered in Y, shifted left in X
# Arduino occupies X from 0 to pcb_w, breadboard from pcb_w+gap to pcb_w+gap+bb_w
# Internal cavity center is at inner_w/2
# Arduino PCB center: X offset from center = -(inner_w/2) + pcb_clearance + pcb_w/2
arduino_x_offset = -(inner_w / 2) + pcb_clearance + pcb_w / 2   # [mm]
arduino_y_offset = 0.0  # [mm] centered in Y (PCB centered in depth)

# Hole positions in absolute coordinates (enclosure center = 0,0)
hole_positions = [
    (arduino_x_offset - pcb_w / 2 + hx,
     arduino_y_offset - pcb_d / 2 + hy)
    for hx, hy in arduino_holes
]

# === OUTPUT ===
out_dir = os.path.dirname(os.path.abspath(__file__))


def make_outer_shell():
    """Outer box with fillet on vertical edges — BEFORE booleans."""
    outer = (
        cq.Workplane("XY")
        .box(outer_w, outer_d, outer_h)
        .translate((0, 0, outer_h / 2))
        .edges("|Z")
        .fillet(fillet_r)
    )
    return outer


def make_cavity(outer):
    """Hollows out the internal cavity."""
    cavity = (
        cq.Workplane("XY")
        .box(inner_w, inner_d, inner_h)
        .translate((0, 0, floor_t + inner_h / 2))
    )
    return outer.cut(cavity)


def add_standoffs(body):
    """Adds 4x M3 standoffs at the exact Arduino PCB hole positions."""
    for (mx, my) in hole_positions:
        # Cylindrical standoff
        standoff = (
            cq.Workplane("XY")
            .circle(standoff_od / 2)
            .extrude(standoff_h)
            .translate((mx, my, floor_t))
        )
        body = body.union(standoff)

        # Hole in standoff
        hole = (
            cq.Workplane("XY")
            .circle(mount_hole_d / 2)
            .extrude(standoff_h + floor_t + 1)
            .translate((mx, my, 0))
        )
        body = body.cut(hole)
    return body


def add_apertures(body):
    """Cuts USB-B and DC jack openings on the right side (positive X of Arduino PCB)."""
    cut_depth = wall + 2  # [mm] to cut through entire wall

    # USB/DC side is where X of PCB = pcb_w, i.e. absolute X = arduino_x_offset + pcb_w/2
    # This corresponds to the right edge of the Arduino
    # The opening goes on the outer wall at X = outer_w/2
    wall_x = outer_w / 2  # [mm] cut center on right wall

    # USB-B
    usb_z_center = floor_t + standoff_h + pcb_thick + usb_h / 2  # [mm] Z center
    usb_y_abs = arduino_y_offset - pcb_d / 2 + usb_y_center       # [mm] absolute Y center
    usb_cut = (
        cq.Workplane("XY")
        .box(cut_depth, usb_w, usb_h)
        .translate((wall_x, usb_y_abs, usb_z_center))
    )
    body = body.cut(usb_cut)

    # DC jack
    dc_z_center = floor_t + standoff_h + pcb_thick + dc_h / 2  # [mm]
    dc_y_abs = arduino_y_offset - pcb_d / 2 + dc_y_center       # [mm]
    dc_cut = (
        cq.Workplane("XY")
        .box(cut_depth, dc_w, dc_h)
        .translate((wall_x, dc_y_abs, dc_z_center))
    )
    body = body.cut(dc_cut)

    return body


def add_snap_recesses(body):
    """Adds snap-fit recesses on internal walls of the body (long sides)."""
    # 2 snaps per long side (4 total)
    snap_positions_x = [-inner_w / 4, inner_w / 4]  # [mm]

    for sx in snap_positions_x:
        for y_sign in [1, -1]:
            y_pos = y_sign * (outer_d / 2 - wall / 2)  # [mm]
            recess = (
                cq.Workplane("XY")
                .box(snap_w, wall + 1, snap_h)
                .translate((sx, y_pos, outer_h - snap_h / 2))
            )
            body = body.cut(recess)
    return body


def make_body():
    """Assembles the enclosure body."""
    body = make_outer_shell()
    body = make_cavity(body)
    body = add_standoffs(body)
    body = add_apertures(body)
    body = add_snap_recesses(body)
    return body


def make_lid():
    """Lid with interlocking lip and snap-fit hooks."""
    # Flat top plate
    top = (
        cq.Workplane("XY")
        .box(outer_w, outer_d, lid_t)
        .translate((0, 0, lid_t / 2))
        .edges("|Z")
        .fillet(fillet_r)
    )

    # Interlocking lip
    lip_w = inner_w - 2 * lip_gap    # [mm]
    lip_d = inner_d - 2 * lip_gap    # [mm]
    lip_outer = (
        cq.Workplane("XY")
        .box(lip_w, lip_d, lip_h)
        .translate((0, 0, -lip_h / 2))
    )
    lip_inner = (
        cq.Workplane("XY")
        .box(lip_w - 2 * wall, lip_d - 2 * wall, lip_h + 1)
        .translate((0, 0, -lip_h / 2))
    )
    lid = top.union(lip_outer).cut(lip_inner)

    # Snap-fit hooks (4 hooks on long sides)
    snap_positions_x = [-inner_w / 4, inner_w / 4]  # [mm]

    for sx in snap_positions_x:
        for y_sign in [1, -1]:
            y_base = y_sign * (lip_d / 2 - wall / 2)  # [mm]
            # Hook: block protruding outward
            hook = (
                cq.Workplane("XY")
                .box(snap_w, snap_overhang, snap_h)
                .translate((
                    sx,
                    y_base + y_sign * snap_overhang / 2,
                    -lip_h + snap_h / 2
                ))
            )
            lid = lid.union(hook)

    return lid


def add_vent_grid(lid):
    """Ventilation grid on the lid: rectangular slots."""
    start_x = -(vent_n - 1) * vent_gap / 2  # [mm] first slot position

    for i in range(vent_n):
        x_pos = start_x + i * vent_gap  # [mm]
        slot = (
            cq.Workplane("XY")
            .box(vent_slot_w, vent_slot_l, lid_t + 2)
            .translate((x_pos, 0, lid_t / 2))
        )
        lid = lid.cut(slot)
    return lid


def make_lid_complete():
    """Lid with ventilation."""
    lid = make_lid()
    lid = add_vent_grid(lid)
    return lid


# === EXPORT ===
body = make_body()
lid = make_lid_complete()

# Body
body_step = os.path.join(out_dir, "arduino_enclosure.step")
body_stl  = os.path.join(out_dir, "arduino_enclosure.stl")
cq.exporters.export(body, body_step)
cq.exporters.export(body, body_stl)

# Lid
lid_step = os.path.join(out_dir, "arduino_enclosure_lid.step")
lid_stl  = os.path.join(out_dir, "arduino_enclosure_lid.stl")
cq.exporters.export(lid, lid_step)
cq.exporters.export(lid, lid_stl)

# Assembly
assy = cq.Assembly()
assy.add(body, name="body", color=cq.Color(0.27, 0.51, 0.71))  # steel blue
assy.add(
    lid, name="lid",
    loc=cq.Location((0, 0, outer_h + 2)),  # raised for visualization
    color=cq.Color(0.9, 0.9, 0.9)  # light gray
)
assy_step = os.path.join(out_dir, "arduino_enclosure_assembly.step")
assy.save(assy_step)

# === REPORT ===
print("=" * 55)
print("  REPORT — Arduino Uno Rev3 Enclosure (PETG)")
print("=" * 55)

for name, part in [("BODY", body), ("LID", lid)]:
    bb = part.val().BoundingBox()
    vol = part.val().Volume()
    vol_cm3 = vol / 1000
    weight_g = vol_cm3 * 1.27 * (0.3 + 0.7 * 0.20)  # PETG, 20% infill
    time_h = (vol_cm3 / 20) * 1.3
    hours = int(time_h)
    minutes = int((time_h - hours) * 60)

    print(f"\n{name}:")
    print(f"  BB: {bb.xlen:.1f} x {bb.ylen:.1f} x {bb.zlen:.1f} mm")
    print(f"  Volume: {vol:,.0f} mm3 ({vol_cm3:.1f} cm3)")
    print(f"  Estimated weight: {weight_g:.1f}g (PETG, 20% infill)")
    print(f"  Estimated time: ~{hours}h {minutes}min")

print(f"\nMaterial: PETG")
print(f"  wall_min: 1.2mm (used: {wall}mm) OK")
print(f"  Fillet: {fillet_r}mm on vertical edges")
print(f"  Enclosed chamber: not required")
print(f"  Drying: 65C x 4h recommended")

print(f"\nInternal dimensions:")
print(f"  Width: {inner_w:.1f}mm (Arduino {pcb_w}+gap {bb_gap}+breadboard {bb_w}+clearance)")
print(f"  Depth: {inner_d:.1f}mm (PCB {pcb_d}+clearance)")
print(f"  Height: {inner_h:.1f}mm (standoff {standoff_h}+PCB {pcb_thick}+comp {comp_h})")

print(f"\nM3 holes: {len(hole_positions)} positions")
for i, (hx, hy) in enumerate(hole_positions):
    print(f"  Hole {i+1}: ({hx:.2f}, {hy:.2f})")

print(f"\nExported files:")
print(f"  {body_step}")
print(f"  {body_stl}")
print(f"  {lid_step}")
print(f"  {lid_stl}")
print(f"  {assy_step}")
print("=" * 55)
